/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;

/**
 *
 * @author s.marcerou
 */
public class AddUserDialog extends javax.swing.JDialog {

    private PropertyChangeSupport listeners = new PropertyChangeSupport(this);

    public void addPropertyChangeListener(PropertyChangeListener l) {
        this.listeners.addPropertyChangeListener(l);
    }

    /**
     * Creates new form AddUserDialog
     */
    public AddUserDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//     inserte.addActionListener(e -> {
//         frame.dispose()
//     });
    }

    // get
    public String getPrenom() {
        return this.addPrenomUser.getText();
    }

    public String getNom() {
        return this.addNomUser.getText();
    }

    public String getIdentifiant() {
        return this.addIdentifitantUser.getText();
    }

    public String getMotDePasse() {
        return this.addMotDePasseUser.getText();
    }

    public String getAdresseEmail() {
        return this.addEmailUser.getText();
    }

    // Set
    public void setPrenom(String prenom) {
        this.addPrenomUser.setText(prenom);
    }

    public void setNom(String nom) {
        this.addNomUser.setText(nom);
    }

    public void setIdentifiant(String identifiant) {
        this.addIdentifitantUser.setText(identifiant);
    }

    public void setMotDePasse(String motDePasse) {
        this.addMotDePasseUser.setText(motDePasse);
    }

    public void setAdresseEmail(String adresseEmail) {
        this.addEmailUser.setText(adresseEmail);
    }

    //set defaultData
    public void setDefaultData() {
        this.addPrenomUser.setText("");
        this.addNomUser.setText("");
        this.addIdentifitantUser.setText("");
        this.addMotDePasseUser.setText("");
        this.addEmailUser.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        mpd = new javax.swing.JLabel();
        identifiant = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        ValideAjoutUser = new javax.swing.JButton();
        addPrenomUser = new javax.swing.JTextField();
        addNomUser = new javax.swing.JTextField();
        addIdentifitantUser = new javax.swing.JTextField();
        addMotDePasseUser = new javax.swing.JTextField();
        addEmailUser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        name.setText("prenom");

        prenom.setText("nom");

        mpd.setText("mot de passe");

        identifiant.setText("Identifitant");

        mail.setText("adresse mail");

        ValideAjoutUser.setText("Valider");
        ValideAjoutUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValideAjoutUserActionPerformed(evt);
            }
        });

        addPrenomUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPrenomUserActionPerformed(evt);
            }
        });

        addNomUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNomUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(mail))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(identifiant)
                                            .addComponent(prenom, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(mpd, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(name))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addPrenomUser, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(addNomUser)
                            .addComponent(addIdentifitantUser)
                            .addComponent(addMotDePasseUser)
                            .addComponent(addEmailUser)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(ValideAjoutUser)))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPrenomUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNomUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenom))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addIdentifitantUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identifiant))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMotDePasseUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mpd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mail))
                .addGap(98, 98, 98)
                .addComponent(ValideAjoutUser)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValideAjoutUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValideAjoutUserActionPerformed
        // TODO add your handling code here:
        listeners.firePropertyChange("ValideAjoutUser", null, null);
    }//GEN-LAST:event_ValideAjoutUserActionPerformed

    private void addPrenomUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPrenomUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPrenomUserActionPerformed

    private void addNomUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNomUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNomUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddUserDialog dialog = new AddUserDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ValideAjoutUser;
    private javax.swing.JTextField addEmailUser;
    private javax.swing.JTextField addIdentifitantUser;
    private javax.swing.JTextField addMotDePasseUser;
    private javax.swing.JTextField addNomUser;
    private javax.swing.JTextField addPrenomUser;
    private javax.swing.JLabel identifiant;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel mpd;
    private javax.swing.JLabel name;
    private javax.swing.JLabel prenom;
    // End of variables declaration//GEN-END:variables
}
